### ISSUE TITLE
To-Do List for Kari

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#14]
This issue is a list of code Kari still needs to write/rearrange:

- [x] Clean the newest SWC data and load into the script
- [x] Un-comment lines 73 and 74
- [x] Line 103 for SWC (why are you attending this workshop?)
- [x] Line 146 for SWC (How did you find out about this workshop?)
- [x] Line 165 for SWC (workshop environment)
- [x] Line 178 for SWC (Perception of instructors and helpers)
- [x] Line 215 for SWC (How much information was new?)
- [x] Line 303 for SWC (Language covered)
- [x] Line 332 for SWC (Perspectives of self-reported skills and confidence)
- [x] Line 605 SWC (NPS or Likely to recommend)
- [x] Line 606 SWC/DC (Qualitative Analysis)
- [x] Line 638 SWC (Domain)
- [x] Line 655 SWC (Position)
- [x] Line 702 SWC (1st time attending)

**Comment by kariljordan** [comment]
SWC does not have a language covered question.
